apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync
  namespace: configsync-devops
  # annotations:
  #   configmanagement.gke.io/cluster-selector: dev-clusters 
#hi
spec:
  sourceType: git
  sourceFormat: unstructured
  git:
    repo: https://github.com/nani454554/applicationreposync.git
    branch: main
    dir: application-namespace-config/namespaces/configsync-devops/deployment-manifests
    auth: token
    secretRef:
      name: nikhil
